/**
 * Password reset — minimum viable flow without an email provider.
 *
 * v1: a recovery token is generated by `requestPasswordReset`, stored on
 * the `passwordResetTokens` table with a 30-min expiry. The matching
 * reset URL is logged server-side for the alumna to find in the dev
 * console — once `RESEND_API_KEY` is set, the same action emails the
 * URL. `resetPassword({ token, newPassword })` validates the token,
 * rehashes the password with Scrypt, and updates the `authAccounts` row.
 */

"use node";

import { v } from "convex/values";
import { ConvexError } from "convex/values";
import { Scrypt } from "lucia";
import { internalAction } from "./_generated/server";
import { internal } from "./_generated/api";

const TOKEN_TTL_MS = 30 * 60 * 1000;
const MIN_PASSWORD_LENGTH = 12;

function randomToken(): string {
  const bytes = new Uint8Array(24);
  crypto.getRandomValues(bytes);
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

export const requestPasswordReset = internalAction({
  args: { email: v.string() },
  handler: async (
    ctx,
    { email },
  ): Promise<{ ok: true; resetUrl?: string }> => {
    const normalized = email.trim().toLowerCase();
    const account = await ctx.runQuery(
      internal.authResetHelpers.findPasswordAccount,
      { email: normalized },
    );
    // Always pretend success — don't leak which emails exist.
    if (!account) return { ok: true };

    const token = randomToken();
    const expiresAt = Date.now() + TOKEN_TTL_MS;
    await ctx.runMutation(internal.authResetHelpers.storeResetToken, {
      userId: account.userId,
      token,
      expiresAt,
    });

    const appUrl =
      process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000";
    const resetUrl = `${appUrl}/reset-password?token=${token}`;

    // Email delivery — wired once RESEND_API_KEY + verified domain land.
    // For now we log + return so the dev/demo flow still works.
    console.log("[password-reset] sending link", {
      email: normalized,
      resetUrl,
    });

    return { ok: true, resetUrl };
  },
});

export const resetPassword = internalAction({
  args: { token: v.string(), newPassword: v.string() },
  handler: async (ctx, { token, newPassword }): Promise<{ ok: true }> => {
    if (newPassword.length < MIN_PASSWORD_LENGTH) {
      throw new ConvexError({
        code: "weak-password",
        message: `Password must be at least ${MIN_PASSWORD_LENGTH} characters`,
      });
    }
    const row = await ctx.runMutation(
      internal.authResetHelpers.consumeResetToken,
      { token },
    );
    if (!row) {
      throw new ConvexError({
        code: "invalid-token",
        message:
          "Reset link is invalid or expired. Request a new one from /forgot-password.",
      });
    }
    const hash = await new Scrypt().hash(newPassword);
    await ctx.runMutation(internal.authResetHelpers.updatePasswordHash, {
      userId: row.userId,
      passwordHash: hash,
    });
    return { ok: true };
  },
});
