/**
 * Activity feed + posts (Epic 8).
 *
 * Feed surfaces verified alumni posts in reverse chronological order, scoped
 * by visibility tier (connections or alumni-only). Plan accepts the feed will
 * be quiet — implementation matches the UX spec's "specificity over abundance"
 * principle: chronological, no engagement bait.
 */

import { v } from "convex/values";
import { ConvexError } from "convex/values";
import { getAuthUserId } from "@convex-dev/auth/server";
import type { Doc, Id } from "./_generated/dataModel";
import {
  internalMutation,
  mutation,
  query,
  type QueryCtx,
} from "./_generated/server";

const POST_MAX_LENGTH = 2000;
const FEED_PAGE_DEFAULT = 30;

async function isConnectedTo(
  ctx: QueryCtx,
  meId: Id<"users">,
  otherId: Id<"users">,
): Promise<boolean> {
  const [a, b] = meId < otherId ? [meId, otherId] : [otherId, meId];
  const row = await ctx.db
    .query("connections")
    .withIndex("by_pair", (q) => q.eq("userA", a).eq("userB", b))
    .unique();
  return !!row && row.status === "connected";
}

// @no-audit-required: user self-service; author posts to their own feed.
export const publishPost = mutation({
  args: {
    content: v.string(),
    visibilityTier: v.string(),
    imageStorageId: v.optional(v.id("_storage")),
  },
  handler: async (ctx, { content, visibilityTier, imageStorageId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new ConvexError({
        code: "unauthenticated",
        message: "Sign in required",
      });
    }
    const trimmed = content.trim();
    if (trimmed.length === 0) {
      throw new ConvexError({
        code: "empty",
        message: "Post content cannot be empty",
      });
    }
    if (trimmed.length > POST_MAX_LENGTH) {
      throw new ConvexError({
        code: "too-long",
        message: `Post must be ${POST_MAX_LENGTH} characters or fewer`,
      });
    }
    if (visibilityTier !== "connections" && visibilityTier !== "alumni") {
      throw new ConvexError({
        code: "invalid-visibility",
        message: "visibilityTier must be 'connections' or 'alumni'",
      });
    }
    const id = await ctx.db.insert("posts", {
      authorId: userId,
      kind: imageStorageId ? "image" : "text",
      content: trimmed,
      imageStorageId,
      visibilityTier,
      autoGenerated: false,
      createdAt: Date.now(),
    });
    return { postId: id };
  },
});

// @no-audit-required: user self-service; author deletes their own post.
export const deletePost = mutation({
  args: { postId: v.id("posts") },
  handler: async (ctx, { postId }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new ConvexError({
        code: "unauthenticated",
        message: "Sign in required",
      });
    }
    const post = await ctx.db.get(postId);
    if (!post) return { ok: true };
    if (post.authorId !== userId) {
      throw new ConvexError({
        code: "forbidden",
        message: "Only the author can delete this post",
      });
    }
    if (post.imageStorageId) await ctx.storage.delete(post.imageStorageId);
    await ctx.db.delete(postId);
    return { ok: true };
  },
});

/**
 * Get the authenticated user's chronological feed.
 * Includes: connections' connection-tier posts + everyone's alumni-tier posts.
 * Filters out deleted posts and posts from suspended/deleted authors.
 */
export const getFeed = query({
  args: { limit: v.optional(v.number()) },
  handler: async (ctx, { limit }) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) return [];
    const pageSize = limit ?? FEED_PAGE_DEFAULT;

    const recent = await ctx.db
      .query("posts")
      .withIndex("by_time")
      .order("desc")
      .take(pageSize * 4);

    const visible: Array<{
      _id: Id<"posts">;
      authorId: Id<"users">;
      authorName: string | null;
      authorSlug: string | null;
      kind: string;
      content: string;
      imageUrl: string | null;
      autoGenerated: boolean;
      createdAt: number;
    }> = [];
    for (const p of recent) {
      if (p.deletedAt) continue;
      const author = await ctx.db.get(p.authorId);
      if (!author || author.deletedAt || author.suspendedAt) continue;
      if (p.visibilityTier === "connections" && p.authorId !== userId) {
        const ok = await isConnectedTo(ctx, userId, p.authorId);
        if (!ok) continue;
      }
      const authorProfile = await ctx.db
        .query("profiles")
        .withIndex("by_userId", (q) => q.eq("userId", p.authorId))
        .unique();
      visible.push({
        _id: p._id,
        authorId: p.authorId,
        authorName: authorProfile?.displayName ?? author.name ?? null,
        authorSlug: authorProfile?.slug ?? null,
        kind: p.kind,
        content: p.content,
        imageUrl: p.imageStorageId
          ? await ctx.storage.getUrl(p.imageStorageId)
          : null,
        autoGenerated: p.autoGenerated,
        createdAt: p.createdAt,
      });
      if (visible.length >= pageSize) break;
    }
    return visible;
  },
});

// @no-audit-required: helper for upload widget; ephemeral token only.
export const generatePostImageUploadUrl = mutation({
  args: {},
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) {
      throw new ConvexError({
        code: "unauthenticated",
        message: "Sign in required",
      });
    }
    return await ctx.storage.generateUploadUrl();
  },
});

/**
 * Story 8.3 — auto-generate work-anniversary milestone posts.
 * Runs daily; finds verified profiles whose experience entries cross a year
 * boundary today, and inserts an autoGenerated post (visibility = alumni).
 *
 * "Year boundary" heuristic: if the experience.years string starts with a
 * 4-digit year, treat that year + N as the anniversary. Best-effort — users
 * with unstructured `years` fields are skipped.
 */
export const generateWorkAnniversaryPosts = internalMutation({
  args: {},
  handler: async (ctx) => {
    const now = new Date();
    const todayMonth = now.getUTCMonth();
    const todayDay = now.getUTCDate();
    const todayYear = now.getUTCFullYear();

    // @no-privacy-required: internal cron iterating verified profiles to generate auto-posts; no viewer-facing read.
    const profiles = await ctx.db.query("profiles").collect();
    let posted = 0;

    for (const p of profiles) {
      if (p.verifiedAt == null) continue;
      const user = await ctx.db.get(p.userId);
      if (!user || user.deletedAt || user.suspendedAt) continue;

      // Check notificationPrefs — opt-out via "milestonesAuto"
      const prefs = await ctx.db
        .query("notificationPrefs")
        .withIndex("by_user", (q) => q.eq("userId", p.userId))
        .unique();
      if (prefs?.prefs?.milestonesAuto === false) continue;

      for (const exp of p.experience ?? []) {
        const yearMatch = /^(\d{4})/.exec(exp.years ?? "");
        if (!yearMatch) continue;
        const startYear = Number(yearMatch[1]);
        const years = todayYear - startYear;
        if (years < 1) continue;
        // Use the profile's createdAt month/day as the anniversary anchor.
        // (We don't know the precise start date; closest signal we have.)
        if (
          new Date(p.createdAt).getUTCMonth() !== todayMonth ||
          new Date(p.createdAt).getUTCDate() !== todayDay
        )
          continue;
        // Dedup: skip if we already generated this anniversary in the last 25h
        const yesterdayMs = Date.now() - 25 * 60 * 60 * 1000;
        const recent = await ctx.db
          .query("posts")
          .withIndex("by_author_time", (q) =>
            q.eq("authorId", p.userId).gte("createdAt", yesterdayMs),
          )
          .collect();
        const already = recent.some(
          (r) =>
            r.kind === "work-anniversary" &&
            r.relatedMetadata &&
            (r.relatedMetadata as Record<string, unknown>).role === exp.role &&
            (r.relatedMetadata as Record<string, unknown>).company ===
              exp.company,
        );
        if (already) continue;

        await ctx.db.insert("posts", {
          authorId: p.userId,
          kind: "work-anniversary",
          content: `${p.displayName} celebrates ${years} ${
            years === 1 ? "year" : "years"
          } at ${exp.company}.`,
          visibilityTier: "alumni",
          autoGenerated: true,
          relatedMetadata: { role: exp.role, company: exp.company, years },
          createdAt: Date.now(),
        });
        posted += 1;
      }
    }
    return { posted };
  },
});

/**
 * Return the type marker for callers; consumed by privacy lint to ensure
 * we don't accidentally treat this as a profile-fetcher.
 */
void (null as unknown as Doc<"posts">);
