"use client";

/**
 * Feed page (ported from Claude Design prototype).
 *
 * Two-column layout: main feed (greeting hero + composer + posts) + right
 * rail (matched jobs, upcoming events, suggested people, footer).
 * Composer is always visible to authenticated users; on empty feed we still
 * show composer + rail rather than a dead-end empty state.
 */

import { useState } from "react";
import Link from "next/link";
import { useMutation, useQuery } from "convex/react";
import { toast } from "sonner";
import {
  ArrowRight,
  Briefcase,
  Calendar,
  Loader2,
  Send,
  Sparkles,
  Trash2,
  Users,
} from "lucide-react";
import { api } from "@/lib/convex-api";
import { AUFAvatar } from "@/components/auf/AUFAvatar";

type Post = {
  _id: string;
  authorId: string;
  authorName: string | null;
  authorSlug: string | null;
  kind: string;
  content: string;
  imageUrl: string | null;
  autoGenerated: boolean;
  createdAt: number;
};

type Job = {
  _id: string;
  title: string;
  employerName: string;
  location: string;
  salaryMin?: number;
  salaryMax?: number;
  salaryCurrency?: string;
};

type EventRow = {
  _id: string;
  title: string;
  startsAt: number;
  locationLabel?: string;
  onlineUrl?: string;
  goingCount: number;
};

type Suggested = {
  _id: string;
  displayName: string;
  currentRole?: string;
  company?: string;
};

function relativeTime(ms: number): string {
  const diff = Date.now() - ms;
  const minutes = Math.round(diff / 60000);
  if (minutes < 1) return "just now";
  if (minutes < 60) return `${minutes}m`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h`;
  const days = Math.round(hours / 24);
  if (days < 7) return `${days}d`;
  return new Date(ms).toLocaleDateString();
}

function firstName(name?: string | null): string {
  if (!name) return "there";
  return name.split(/\s+/)[0] ?? "there";
}

function greeting(): string {
  const h = new Date().getHours();
  if (h < 12) return "Good morning";
  if (h < 18) return "Good afternoon";
  return "Good evening";
}

export default function FeedPage() {
  const me = useQuery(api.users.getMe);
  const myProfile = useQuery(api.profiles.getMyProfile);
  const feed = useQuery(api.feed.getFeed, { limit: 30 });
  const matchedJobs = useQuery(api.jobs.browse, { showUnmatched: true });
  const upcomingEvents = useQuery(api.events.listUpcoming);
  const suggested = useQuery(api.directory.list, { pageSize: 3 });
  const publishPost = useMutation(api.feed.publishPost);
  const deletePost = useMutation(api.feed.deletePost);

  const [draft, setDraft] = useState("");
  const [visibility, setVisibility] = useState<"connections" | "alumni">(
    "connections",
  );
  const [submitting, setSubmitting] = useState(false);

  const onPublish = async () => {
    if (!draft.trim()) return;
    setSubmitting(true);
    try {
      await publishPost({ content: draft.trim(), visibilityTier: visibility });
      toast.success("Posted");
      setDraft("");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Could not post");
    } finally {
      setSubmitting(false);
    }
  };

  const onDelete = async (postId: string) => {
    try {
      await deletePost({ postId: postId as unknown as never });
      toast.success("Deleted");
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Delete failed");
    }
  };

  const posts = (feed ?? []) as Post[];
  type MeSnapshot = { _id: string; name?: string; email?: string } | null;
  type ProfileSnapshot = { displayName?: string } | null;
  const meSnap = (me ?? null) as MeSnapshot;
  const profileSnap = (myProfile ?? null) as ProfileSnapshot;
  const personName =
    profileSnap?.displayName ?? meSnap?.name ?? meSnap?.email ?? null;

  return (
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-4 lg:gap-6 px-4 sm:px-7 py-6">
      {/* Main column */}
      <div className="col-span-12 lg:col-span-8 space-y-5">
        <GreetingHero name={personName} />
        {meSnap && (
          <Composer
            name={personName ?? "you"}
            draft={draft}
            setDraft={setDraft}
            visibility={visibility}
            setVisibility={setVisibility}
            onPublish={onPublish}
            submitting={submitting}
          />
        )}

        {/* Posts */}
        <div className="space-y-4">
          {feed === undefined ? (
            <Loader2 className="mx-auto h-6 w-6 animate-spin ink-3" />
          ) : (
            posts.map((p) => (
              <FeedPost
                key={p._id}
                post={p}
                mine={!!meSnap && p.authorId === meSnap._id}
                onDelete={onDelete}
              />
            ))
          )}
        </div>
      </div>

      {/* Right rail */}
      <aside className="col-span-12 lg:col-span-4 space-y-5">
        <RightCardJobs jobs={(matchedJobs ?? []) as Job[]} />
        <RightCardEvents events={(upcomingEvents ?? []) as EventRow[]} />
        <RightCardSuggested
          suggested={
            (((suggested as { items?: Suggested[] } | undefined)?.items) ??
              []) as Suggested[]
          }
        />
        <FooterCard />
      </aside>
    </div>
  );
}

function GreetingHero({ name }: { name: string | null }) {
  return (
    <div className="auf-card p-6 relative overflow-hidden">
      <div
        className="absolute inset-0 opacity-[0.06] pointer-events-none"
        style={{
          background:
            "radial-gradient(circle at 100% 0%, var(--brand) 0%, transparent 55%), radial-gradient(circle at 0% 100%, var(--gold) 0%, transparent 50%)",
        }}
      />
      <div className="relative flex items-start gap-5">
        <div className="flex-1">
          <div className="section-eyebrow mb-2 flex items-center gap-2">
            <span className="live-dot" /> Today,{" "}
            {new Date().toLocaleDateString("en-US", {
              month: "short",
              day: "numeric",
            })}
          </div>
          <h2 className="font-serif text-[26px] leading-tight font-semibold mb-1">
            {greeting()}, {firstName(name)}.
          </h2>
          <p className="ink-2 text-[15px] max-w-[44ch]">
            Posts from your connections and the wider alumni network land here.
          </p>
          <div className="flex gap-2 mt-4">
            <Link
              href="/jobs"
              className="auf-btn auf-btn-primary"
            >
              <Briefcase size={15} /> See matched jobs
            </Link>
            <Link
              href="/directory"
              className="auf-btn auf-btn-outline"
            >
              <Users size={15} /> Find mentors
            </Link>
          </div>
        </div>
        <ProfileStrength />
      </div>
    </div>
  );
}

function ProfileStrength() {
  // Static for now — replace with a real strength score when /profile/edit
  // emits one. The design uses 82%; we keep it visible to anchor the hero.
  const pct = 82;
  return (
    <div className="hidden md:flex flex-col items-end gap-3 min-w-[180px]">
      <div className="text-right">
        <div className="text-[28px] font-serif font-semibold leading-none">
          {pct}
          <span className="text-base ink-3 font-sans font-medium">%</span>
        </div>
        <div className="text-[11px] uppercase tracking-wider ink-3">
          Profile strength
        </div>
      </div>
      <div className="w-full">
        <div className="h-1.5 rounded-full bg-[var(--surface-2)] overflow-hidden">
          <div className="h-full brand-bg" style={{ width: `${pct}%` }} />
        </div>
        <Link
          href="/profile/edit"
          className="text-[11px] brand-fg mt-1.5 underline underline-offset-2 inline-block"
        >
          Add 2 skills →
        </Link>
      </div>
    </div>
  );
}

function Composer({
  name,
  draft,
  setDraft,
  visibility,
  setVisibility,
  onPublish,
  submitting,
}: {
  name: string;
  draft: string;
  setDraft: (v: string) => void;
  visibility: "connections" | "alumni";
  setVisibility: (v: "connections" | "alumni") => void;
  onPublish: () => void;
  submitting: boolean;
}) {
  return (
    <div className="auf-card p-4">
      <div className="flex items-center gap-3">
        <AUFAvatar name={name} grad={1} size={40} />
        <textarea
          rows={1}
          maxLength={2000}
          placeholder="Share an update, a job, or ask for help…"
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          className="flex-1 text-[14px] px-4 py-2.5 rounded-full bg-[var(--surface-2)] hover:bg-[var(--brand-50)] transition resize-none focus:outline-none focus:ring-2 focus:ring-[var(--brand)]"
        />
      </div>
      {draft.trim() && (
        <div className="flex items-center justify-between gap-2 mt-3 pt-3 border-t auf-hairline">
          <select
            value={visibility}
            onChange={(e) =>
              setVisibility(e.target.value as "connections" | "alumni")
            }
            className="auf-chip cursor-pointer"
          >
            <option value="connections">Connections only</option>
            <option value="alumni">All verified alumni</option>
          </select>
          <button
            className="auf-btn auf-btn-primary auf-btn-sm"
            onClick={onPublish}
            disabled={!draft.trim() || submitting}
          >
            {submitting ? (
              <Loader2 className="h-3.5 w-3.5 animate-spin" />
            ) : (
              <Send className="h-3.5 w-3.5" />
            )}
            Post
          </button>
        </div>
      )}
    </div>
  );
}

function FeedPost({
  post,
  mine,
  onDelete,
}: {
  post: Post;
  mine: boolean;
  onDelete: (id: string) => void;
}) {
  return (
    <div className="auf-card p-5">
      <div className="flex items-start gap-3">
        <AUFAvatar name={post.authorName ?? "?"} grad={3} badge size={44} />
        <div className="flex-1 min-w-0">
          <div className="flex flex-wrap items-center gap-2">
            {post.authorSlug ? (
              <Link
                href={`/profile/${post.authorSlug}`}
                className="font-medium text-[14.5px] hover:underline"
              >
                {post.authorName ?? "Unknown alumna"}
              </Link>
            ) : (
              <span className="font-medium text-[14.5px]">
                {post.authorName ?? "Unknown alumna"}
              </span>
            )}
            {post.autoGenerated && (
              <span className="auf-chip auf-chip-brand">
                <Sparkles size={11} /> milestone
              </span>
            )}
          </div>
          <div className="text-[12.5px] ink-3 mt-0.5">
            · {relativeTime(post.createdAt)}
          </div>
        </div>
        {mine && !post.autoGenerated && (
          <button
            onClick={() => onDelete(post._id)}
            className="auf-btn auf-btn-ghost auf-btn-sm"
            aria-label="Delete post"
          >
            <Trash2 className="h-3.5 w-3.5" />
          </button>
        )}
      </div>
      <p className="mt-3 text-[14.5px] leading-[1.55] whitespace-pre-wrap ink">
        {post.content}
      </p>
      {post.imageUrl && (
        // eslint-disable-next-line @next/next/no-img-element
        <img
          src={post.imageUrl}
          alt=""
          className="mt-3 max-h-96 rounded-lg border auf-hairline object-cover w-full"
        />
      )}
    </div>
  );
}

function RightCardJobs({ jobs }: { jobs: Job[] }) {
  return (
    <div className="auf-card p-5">
      <div className="flex items-center justify-between mb-4">
        <div>
          <div className="section-eyebrow">Matched for you</div>
          <h3 className="font-serif text-[17px] font-semibold mt-0.5">
            Jobs from your network
          </h3>
        </div>
        <Link
          href="/jobs"
          className="text-[12px] brand-fg font-medium hover:underline"
        >
          All →
        </Link>
      </div>
      {jobs.length === 0 ? (
        <p className="text-[12.5px] ink-3">
          No matched jobs yet — check the Jobs tab.
        </p>
      ) : (
        <div className="space-y-3">
          {jobs.slice(0, 3).map((j, i) => {
            const initials = (j.employerName ?? "?")
              .split(/\s+/)
              .map((w) => w[0])
              .slice(0, 2)
              .join("");
            const grad = (((i % 6) + 1) as 1 | 2 | 3 | 4 | 5 | 6);
            return (
              <Link
                key={j._id}
                href={`/jobs`}
                className="w-full flex items-start gap-3 p-2.5 -mx-2 rounded-lg hover:bg-[var(--surface-2)] transition"
              >
                <div
                  className={`w-9 h-9 rounded-lg av-grad-${grad} text-white font-serif font-semibold text-sm flex items-center justify-center shrink-0`}
                >
                  {initials}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-[13.5px] font-medium truncate">
                    {j.title}
                  </div>
                  <div className="text-[12px] ink-3 truncate">
                    {j.employerName} · {j.location?.split(" · ")[0]}
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}

function RightCardEvents({ events }: { events: EventRow[] }) {
  return (
    <div className="auf-card p-5">
      <div className="section-eyebrow mb-3">Upcoming</div>
      {events.length === 0 ? (
        <p className="text-[12.5px] ink-3">No upcoming events.</p>
      ) : (
        <div className="space-y-3">
          {events.slice(0, 3).map((e) => {
            const d = new Date(e.startsAt);
            const month = d
              .toLocaleString("en-US", { month: "short" })
              .toUpperCase();
            const day = d.getDate();
            return (
              <Link
                key={e._id}
                href="/events"
                className="flex items-start gap-3 -mx-2 px-2 py-1 rounded-md hover:bg-[var(--surface-2)]"
              >
                <div className="text-center shrink-0 w-12 px-2 py-1.5 rounded-md border auf-hairline">
                  <div className="text-[10px] font-semibold ink-3 tracking-wider">
                    {month}
                  </div>
                  <div className="text-[16px] font-serif font-semibold leading-none mt-0.5">
                    {day}
                  </div>
                </div>
                <div className="flex-1 min-w-0">
                  <div className="text-[13.5px] font-medium leading-tight">
                    {e.title}
                  </div>
                  <div className="text-[12px] ink-3 mt-0.5">
                    {e.locationLabel ?? e.onlineUrl ?? "Online"}
                  </div>
                  <div className="text-[11px] ink-3 mt-1">
                    {e.goingCount} alumni going
                  </div>
                </div>
              </Link>
            );
          })}
        </div>
      )}
    </div>
  );
}

function RightCardSuggested({ suggested }: { suggested: Suggested[] }) {
  return (
    <div className="auf-card p-5">
      <div className="section-eyebrow mb-3">People you may know</div>
      {suggested.length === 0 ? (
        <p className="text-[12.5px] ink-3">
          The directory will surface suggestions as the network grows.
        </p>
      ) : (
        <div className="space-y-3">
          {suggested.slice(0, 3).map((a, i) => {
            const grad = ((i % 6) + 1) as 1 | 2 | 3 | 4 | 5 | 6;
            return (
              <div key={a._id} className="flex items-center gap-3">
                <AUFAvatar name={a.displayName} grad={grad} size={36} />
                <div className="flex-1 min-w-0">
                  <div className="text-[13.5px] font-medium truncate">
                    {a.displayName}
                  </div>
                  <div className="text-[11.5px] ink-3 truncate">
                    {[a.currentRole, a.company].filter(Boolean).join(" · ")}
                  </div>
                </div>
                <Link
                  href="/directory"
                  className="auf-btn auf-btn-outline auf-btn-sm"
                >
                  Connect
                </Link>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}

function FooterCard() {
  return (
    <div className="text-[11px] ink-4 px-1 leading-relaxed">
      <div className="flex flex-wrap gap-x-2 gap-y-1">
        <Link href="/about" className="hover:underline">
          About
        </Link>
        ·
        <Link href="/help" className="hover:underline">
          Help
        </Link>
        ·
        <Link href="/legal/privacy" className="hover:underline">
          Privacy
        </Link>
        ·
        <Link href="/legal/terms" className="hover:underline">
          Terms
        </Link>
        ·
        <Link href="/verify" className="hover:underline">
          Verification
        </Link>
        <span className="inline-flex items-center gap-1 ml-auto">
          <ArrowRight size={11} />
        </span>
      </div>
      <div className="mt-2">
        AUF Alumni Network · Angeles University Foundation · est. 1971
      </div>
    </div>
  );
}
